### ISSUE TITLE
how to register new users? 

### ISSUE THREAD

**Issue by Nagiboshiro** [amitshuu/messenger-app#1]
Dear Amit Shukrun, cool app and nice arch. But, how to register new users?

**Comment by amitshuu** [comment]
Hi @Nagiboshiro ,
Sorry for the late response, I have just updated the repo and added the option to register, take a look [here](https://github.com/amitshuu/messenger-app/blob/main/client/src/pages/Login.tsx)
If you facing another issues, feel free to contact me again!
