### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by oladejostephen** [amitshuu/messenger-app#2]
Please how do i connect my mongo db to the app.

**Comment by amitshuu** [comment]
Hi @oladejostephen ,
you need to create .env file and put these inside:
```
PORT = 5000
MONGO_URL = YOUR MONGODB URL
JWT_SECRET = ANY JWT SECRET CODE
```
Let me know if this fixed your issue.

**Comment by oladejostephen** [comment]
okay, thanks.

**Comment by amitshuu** [comment]
> okay, thanks.

Did this solve your issue?

**Comment by oladejostephen** [comment]
not yet. because i don't know what you mean by mongo db link.

**Comment by amitshuu** [comment]
@oladejostephen 
When you creating a new cluster in mongo db you have an "connect" button.
Click on it and then choose "Connect your application" option, copy the connection string to the .env file
and make sure you replace "password" to your own password.
If you facing another issues, I recomend you watch this tutorial:

https://www.youtube.com/watch?v=bhiEJW5poHU
